pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    // Wir erlauben Repositories in diesem File und bevorzugen sie
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

// Projekt-Metadaten
rootProject.name = "AA TestMenu App"
include(":app")
